### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by corenel** [hardhackerlabs/book#1]
首先感谢 Podwise 的作者们能够出这本书，看了之后收获很大。

不过在阅读的过程中发现了一些 typos（见 [fork](https://github.com/hardhackerlabs/book/compare/main...corenel:book:main)），不清楚本仓库支不支持提 PR 以及对应的贡献流程，所以先提一个 issue 咨询一下。

**Comment by anson0370** [comment]
非常感谢抓虫，欢迎创建 PR ！
目前没有明确的流程，咱们从简就行。
