### ISSUE TITLE
好奇播客平台和播客主理人对转录行为的版权观点？

### ISSUE THREAD

**Issue by ppodxiang** [hardhackerlabs/book#4]
首先赞一下Hackerlabs的创意和执行力，以及非常大方的承认一开始低估用户信息意识，后面让利的行为；

没找到知识星球之外的交流渠道，在这里留言提问：
现在会默认转录top100的节目提供给大家
我没有逐个了解apple/小宇宙的内容政策，但是好奇这样大规模/盈利目的 把Podcast内容转录，是否是平台所允许的，平台是否有主动表达他们的态度呢？
期待解答，不胜感激！

最后再赞一下AI时代的行动力。

**Comment by SaitoWu** [comment]
关于版权的问题，我们首先得把内容区分为两个部分：播客音频的语音转文字结果以及基于此结果之上的 AI 创作内容。

关于 AI 创作的内容，包括 总结、脑图、大纲和金句等本身与原内容差异巨大，所以原则上这里不涉及版权问题。那么，核心就是语音转文字的结果问题了。这部分现阶段播客软件都在争相提供类似的内容，比如 Apple Podcast 在 17.4 之后也会提供逐字稿，Spotify 也在播放器中提供了逐字稿功能，其他包括 Snipd 等新兴播客平台更是卖点之一。Apple Podcast 将播客逐字稿介绍为一个提升音频产品可达性的功能，因为很多用户可能有听障，所以逐字稿默认是转录所有产品的。对于主理人来说，你如果有自己调优过的逐字稿，那么可以替换，仅此而已。

我们当前还没看到 Apple Podcast，Spotify 以及 Snipd 等产品有在为播客主理人为逐字稿支付版税，我们也会关心相关产业的发展，看后续会有怎么样的变化。

> 以上内容仅代表个人观点，欢迎任何形式的批评和指正
