### ISSUE TITLE
Nextjs 和 Go 两个应用是怎么部署以及通信的

### ISSUE THREAD

**Issue by imsobear** [hardhackerlabs/book#5]
两个问题请教下：

1. 部署：Nextjs 和 Go 两个应用是部署在同一个服务器还是不同服务器？
2. 通信：Nextjs 是怎么跟 Go 应用通信的？调用 HTTP 接口？Go 服务提供了单独域名吗？

感谢~

**Comment by anson0370** [comment]
hello,

1. Nextjs 现在是部署在 Vercel 上的，很好用。Golang 则部署在 Azure 。两者间走公网访问，但因为两者间不算高频访问且在同一个大 region ，所以速度尚可。
2. Nextjs server 部分（nodejs）会调 Golang 开放的接口，走 http + 签名。目前是走的 ip 。

**Comment by imsobear** [comment]
@anson0370 感谢~~

两者间不算高频访问这个怎么理解？比如获取页面上的一些播客列表数据这种不会经过 Go 服务吗？Nextjs 直接访问数据库？

**Comment by skoowoo** [comment]
> @anson0370 感谢~~
> 
> 两者间不算高频访问这个怎么理解？比如获取页面上的一些播客列表数据这种不会经过 Go 服务吗？Nextjs 直接访问数据库？

可以这样理解

如果你做过企业的大数据相关的平台，就知道数据平台基本属于后台离线服务，和前台直接面向用户的 web, app 产品端是分离的。

我们这里的 go 服务基本就是构建的后台离线服务，各种数据处理相关的。nextjs 构建的就是直面用户的。彼此之间基本是解耦的。

**Comment by anson0370** [comment]
> @anson0370 感谢~~
> 
> 两者间不算高频访问这个怎么理解？比如获取页面上的一些播客列表数据这种不会经过 Go 服务吗？Nextjs 直接访问数据库？

针对上面一啸的回答我再稍微补充一点。我们所有和用户直接交互的 CRUD 都在 Nextjs 中，就比如你提到的获取用户播客列表。这部分我们通过 Prisma 在 Nextjs 的 server 部分访问 MySQL 。
这部分本质上跑在 Nodejs 中。更准确的讲的话，当我选择把 Nextjs 部署在 Vercel 上时，这部分实际上以 serverless 的方式跑在 AWS lambda 中 。

当然你也可以选择用 golang 做这部分逻辑，将 Nextjs 当做纯粹的前端框架，或把 Nextjs 的 server 端当做纯粹的 BFF 层来用。但这是当你有一个分工明确的前后端团队时才比较合适。否则我个人认为一把梭是最合适的。
特别像 Nextjs 还提供 ServerAction 这种前后端同构调用的 feature（当然 ServerAction 有 ServerAction 自己的局限性）。

**Comment by imsobear** [comment]
@anson0370 @skoowoo 很清晰的回答，感谢两位。简而言之就是 Go 提供偏底层离线服务，Nextjs 提供 Web 服务（API & 渲染），我觉得很棒~

上周看了一个 YouTube 视频讲 full-stack 的 https://www.youtube.com/watch?v=cgxtLOYE2TE&t=3914s&ab_channel=HowAboutTomorrow%3F ，我对里面提到的 Remix/Nextjs 止步于 controller 这个点不是很认同，我觉得至少 model 层是可以做的，至于再底层的 service 我觉得确实交给 Go 或其他纯后端框架更合理。
