### ISSUE TITLE
我可以尝试把书翻译成英文及希伯来文吗？

### ISSUE THREAD

**Issue by dingjee** [hardhackerlabs/book#6]
我想把这篇文章分享给这边的同学和朋友。
另外，从内容展示的体验上来说，所有内容放一页可能对用户更友好些，特别是手机用户（这个不是技术文档）。
例如：https://playbook.samaltman.com/

**Comment by anson0370** [comment]
如果您熟悉 nextra（nextra 支持多语言），可以直接 fork 本 repo ，提交翻译内容后提交 PR ，我们非常乐意进行 merge 。
如果您不熟悉 nextra ，可以提供翻译后的 markdown 文本文件，由我们来并入工程中。
如果您想对翻译后的内容进行转载，请注明出处。非常感谢！

**Comment by dingjee** [comment]
好的 我研究一下
争取搞成第一个选项~💪
